'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),D=require('../assets/marksman-3d/duel.js'),P=require('../assets/marksman-3d/practice.js'),F=require('../assets/marksman-3d/fight.js');
const C=JSON.parse(fs.readFileSync('app-data/practice.json')).champions;
function make(name){const d=D.create({...C[name],name},{...C.Jinx,name:'Jinx'},{lane:true,movements:F.MOVEMENT});d.bot.next=Infinity;d.lane.nextWave=Infinity;return d;}
function minion(d,pos,side=1){const m={id:'test'+d.lane.nextId++,kind:'minion',side,ranged:false,position:pos,health:{...d.enemy.health,max:5000,hp:5000,armor:0,mr:0,mark:null},damage:0,range:0,next:Infinity,gold:30};d.lane.units.push(m);return m;}
function run(d,t){for(let i=0;i<Math.ceil(t/D.DT);i++)D.step(d,D.DT);}
{const d=make('Ezreal'),s=d.player,a=minion(d,[-1,0,0]),b=minion(d,[0,0,0]),off=minion(d,[0,0,4]);assert(P.cast(s,'R'));const event=s.events.at(-1),end=event.target.slice(),arrival=event.arrive;run(d,3);assert(a.health.hp<5000);assert.equal(a.health.hp,b.health.hp);assert.equal(off.health.hp,5000);assert(d.enemy.health.hp<d.enemy.health.max);assert.deepEqual(event.target,end);assert.equal(event.arrive,arrival);const hp=a.health.hp;run(d,1);assert.equal(a.health.hp,hp,'wave hits each minion once');const hits=s.log.filter(x=>x.slot==='R'&&x.parts);assert(hits.length>=3);assert.equal(hits.find(x=>x.parts.magic.raw<Math.max(...hits.map(x=>x.parts.magic.raw))).parts.magic.raw,Math.max(...hits.map(x=>x.parts.magic.raw))*.5);}
{const d=make('Jinx'),s=d.player,a=minion(d,[-1,0,0]),b=minion(d,[-1,0,.7]),off=minion(d,[-1,0,3]),ally=minion(d,[-1,0,.3],0);P.cast(s,'Q');D.lockTarget(d,s,a.id);const mana=s.resource.mana;assert(P.cast(s,'AA'));assert.equal(s.resource.mana,mana-20);run(d,1);assert(a.health.hp<5000);assert.equal(a.health.hp,b.health.hp);assert.equal(off.health.hp,5000);assert.equal(ally.health.hp,5000);assert.equal(s.combat.excitedUntil,0);assert.equal(D.targetLock(d,s).id,a.id);assert.equal(D.pickTarget(d,s,b.position,.1),b.id);assert(!D.lockTarget(d,s,ally.id));a.health.hp=0;assert.equal(D.targetLock(d,s),null);D.lockTarget(d,s,d.lane.towers[1].id);assert.equal(D.frame(d).targetLock.kind,'tower');D.lockTarget(d,s,null);assert.equal(D.frame(d).targetLock,null);}
{const d=make('Jinx'),s=d.player,near=minion(d,[d.enemy.hero[0],0,.5]),block=minion(d,[0,0,0]);assert(P.cast(s,'R'));run(d,2);assert(d.enemy.health.hp<d.enemy.health.max);assert(near.health.hp<5000);assert.equal(block.health.hp,5000,'Jinx R passes minion blockers');const hits=s.log.filter(x=>x.slot==='R'&&x.parts);assert.equal(hits.length,2);assert.equal(hits[1].parts.physical.raw,hits[0].parts.physical.raw*.8);}
{const d=make('Ezreal'),s=d.player,t=d.lane.towers[1];s.hero=[-1,0,0];s.destination=s.hero.slice();d.enemy.hero=[8,0,0];d.enemy.destination=d.enemy.hero.slice();t.position=[3,0,0];t.next=Infinity;const blocker=minion(d,[0,0,0]);assert(D.lockTarget(d,s,t.id));assert(P.cast(s,'W'));run(d,1);assert(t.health.mark);assert.equal(blocker.health.mark,null);assert(P.cast(s,'AA'));run(d,1);assert.equal(t.health.mark,null);assert.equal(s.log.filter(x=>x.slot==='W detonation').length,1);}
{const d=make('Jinx'),s=d.player;s.hero=[0,0,0];s.destination=s.hero.slice();d.enemy.hero=[2,0,0];d.enemy.destination=d.enemy.hero.slice();d.enemy.health.hp=1;const m=minion(d,[2,0,.4]);P.cast(s,'Q');D.lockTarget(d,s,m.id);assert(P.cast(s,'AA'));run(d,1);assert.equal(d.enemy.health.hp,0);assert(s.combat.excitedUntil>s.time,'splash champion kill grants excitement');}
{const d=make('Ezreal'),s=d.player;s.hero=[0,0,0];s.destination=s.hero.slice();d.enemy.hero=[10,0,0];d.enemy.destination=d.enemy.hero.slice();s.autoApproach=false;D.lockTarget(d,s,'enemy');P.holdAttack(s,true);assert(!P.cast(s,'AA'));run(d,.5);assert.deepEqual(s.hero,[0,0,0],'held AA must never move toward an out-of-range target');P.move(s,[-5,0,0]);run(d,.3);assert(s.hero[0]<-.1,'movement works while AA is held');assert.equal(D.targetLock(d,s).id,'enemy','movement preserves selected target');}
{const d=make('Jinx'),s=d.player;s.autoApproach=false;s.attackAim=[.6,0,.8];for(const rocket of[false,true]){if(rocket)P.cast(s,'Q');const f=D.frame(d),a=f.attackAim;assert.deepEqual(a.start,s.hero);assert(Math.abs(Math.hypot(a.end[0]-a.start[0],a.end[2]-a.start[2])-P.stats(s).range/100)<1e-9,'line ends at current AA range');}s.hero=[1,0,2];assert.deepEqual(D.frame(d).attackAim.start,s.hero);s.attackAim=null;assert.equal(D.frame(d).attackAim,null);}
console.log('PASS lane multi-hit, manual movement, target lock and AA selection line at current attack range');
