'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),D=require('../assets/marksman-3d/duel.js'),P=require('../assets/marksman-3d/practice.js'),F=require('../assets/marksman-3d/fight.js'),Bot=require('../assets/marksman-3d/duel-bot.js');
const C=JSON.parse(fs.readFileSync('app-data/practice.json')).champions;
const make=()=>{const d=D.create({...C.Ezreal,name:'Ezreal'},{...C.Jinx,name:'Jinx'},{lane:true,movements:F.MOVEMENT,difficulty:'hard'});d.bot.next=Infinity;return d;};
const run=(d,t)=>{for(let i=0;i<Math.ceil(t/D.DT);i++)D.step(d,D.DT);};
function minion(d,side,pos,hp=450){const m={id:'test'+d.lane.nextId++,kind:'minion',side,ranged:false,position:pos,health:{...d.enemy.health,max:hp,hp,armor:15,mr:15,mark:null,first:null,total:0,count:0},damage:24,range:.7,next:Infinity,gold:30};d.lane.units.push(m);return m;}
{const d=make(),stats=P.stats(d.player);run(d,.1);assert.equal(d.lane.wave,1);assert.equal(d.lane.units.length,8);assert.deepEqual(P.stats(d.player),stats,'lane never boosts champion stats');const r=D.frame(d);assert.equal(r.lane.units.length,8);assert.equal(r.lane.towers.length,2);}
// Attack target is captured at cast time; switching selection does not redirect a projectile.
{const d=make();d.lane.nextWave=Infinity;const m=minion(d,1,[-1,0,0],1),hp=d.enemy.health.hp;assert(D.selectTarget(d,d.player,m.id));assert(P.cast(d.player,'AA'));D.selectTarget(d,d.player,'enemy');run(d,1);assert.equal(m.health.hp,0);assert.equal(d.player.training.cs,1);assert.equal(d.player.training.gold,30);assert.equal(d.enemy.health.hp,hp);run(d,1);assert.equal(d.player.training.cs,1,'last hit reward is unique');}
// A minion blocks Mystic Shot, but never redirects its damage into the champion.
{const d=make();d.lane.nextWave=Infinity;const m=minion(d,1,[-1,0,0]),hp=d.enemy.health.hp;assert(P.cast(d.player,'Q'));run(d,1);assert(m.health.hp<m.health.max);assert.equal(d.enemy.health.hp,hp);assert.equal(d.player.training.casts,1);assert.equal(d.player.training.hits,1);}
{const d=make();d.lane.nextWave=Infinity;d.player.hero=[15,0,0];d.player.destination=d.player.hero.slice();d.enemy.hero=[17,0,0];d.enemy.destination=d.enemy.hero.slice();const m=minion(d,0,[16,0,0],5000);run(d,.1);assert(d.lane.shots.some(s=>s.tower&&s.target===m.id),'tower prioritizes minions');D.selectTarget(d,d.player,'enemy');assert(P.cast(d.player,'AA'));run(d,1.5);assert.equal(d.lane.towers[1].aggro,'player','champion damage draws tower aggro');assert(d.player.training.towerHits>0);}
{const d=make();d.lane.nextWave=Infinity;d.player.hero=[15,0,0];d.player.destination=d.player.hero.slice();d.enemy.hero=[-10,0,0];d.enemy.destination=d.enemy.hero.slice();const hp=d.player.health.hp;run(d,1);assert(d.player.health.hp<hp,'unprotected champion receives tower damage');}
{const d=make();d.lane.nextWave=Infinity;d.player.hero=[15,0,0];d.player.destination=d.player.hero.slice();const tower=d.lane.towers[1];tower.health.hp=1;assert(D.selectTarget(d,d.player,tower.id));assert(P.cast(d.player,'AA'));run(d,1);assert.equal(d.result,'victory');assert.equal(tower.health.hp,0);}
// AI decisions use delayed public minion HP and tower positions; difficulty changes no stats.
{const self={...D.selfActor(make().enemy),position:[0,0,0],hp:1000,max:1000,locked:false,attackReady:0};const view={time:0,enemy:{champion:'Ezreal',position:[5,0,0],velocity:[0,0,0],hp:1000,max:1000,casts:[],hits:[]},lane:{side:1,ad:100,minions:[{id:'low',side:0,hp:10,position:[1,0,0]}],towers:[]}};const bot=Bot.create('hard',1);Bot.observe(bot,view);const cmd=Bot.decide(bot,self,1);assert.equal(cmd.reason,'last hit');assert.equal(cmd.targetId,'low');}
{const d=make();run(d,1);const report=D.finish(d),before=d.time;assert.equal(report.result,'stopped');assert(report.player.attackIdle>=0);assert(!P.cast(d.player,'Q'));D.step(d,1);assert.equal(d.time,before);assert.equal(report.player.accuracy,null,'no casts is not 0% accuracy');}
{const d=make();d.lane.nextWave=Infinity;d.player.hero=[-10,0,0];d.enemy.hero=[10,0,0];const m=minion(d,0,[11,0,0],1);D.selectTarget(d,d.enemy,m.id);assert(P.cast(d.enemy,'AA'));run(d,1);assert.equal(d.enemy.training.cs,1);assert.equal(d.enemy.combat.excitedUntil,0,'Jinx does not gain champion-kill excitement from minion last hits');}
{const self={...D.selfActor(make().enemy),position:[-16,0,0],hp:1000,max:1000,locked:false};const bot=Bot.create('hard',1);Bot.observe(bot,{time:0,enemy:{champion:'Ezreal',position:[-18,0,0],velocity:[0,0,0],hp:1000,max:1000,casts:[],hits:[]},lane:{side:1,ad:100,minions:[],towers:[{id:'t',side:0,position:[-19,0,0],range:6.5},{id:'home',side:1,position:[19,0,0],range:6.5}]}});assert.equal(Bot.decide(bot,self,1).reason,'tower retreat');}
{const d=make();d.duration=120;for(const s of[d.player,d.enemy])s.health.max=s.health.hp=1000000;for(let i=0;i<400;i++)D.step(d,.25);assert.equal(d.lane.wave,5);assert(d.lane.units.length<=40);assert(d.lane.shots.length<80);for(const m of d.lane.units)assert(m.position.every(Number.isFinite));}
console.log('PASS lane training: equal stats, waves, locked AA targets, unique last hits, Q blockers, tower aggro/damage/destruction, delayed farm AI, honest report, finish, long-run bounds');
