'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),T=require('three');
const Geo=require('../assets/marksman-3d/geometry.js'),Practice=require('../assets/marksman-3d/practice.js'),Fight=require('../assets/marksman-3d/fight.js');
const profiles=JSON.parse(fs.readFileSync('data/marksman-art-direction.json')).champions,geometry=JSON.parse(fs.readFileSync('data/marksman-skill-geometry.json')).champions,catalogue=JSON.parse(fs.readFileSync('data/marksman-ability-catalogue.json')).champions;
for(const[name,p]of Object.entries(profiles)){p.name=name;p.hud={geometry:geometry[name],abilities:Object.fromEntries(Object.entries(catalogue[name].abilities).map(([k,a])=>[k,{cooldowns:a.cooldown_by_rank}]))};for(const slot of['AA','P','Q','W','E','R'])for(const aim of[[0,0,0],[999,0,999],[-999,0,-999]]){const ind=Geo.indicator(p,slot,[-2,0,0],aim,[2,0,0],{rank:4,level:15},Fight.MOVEMENT);assert(ind.endpoint.every(Number.isFinite));if(ind.movementVerified&&ind.range!==null&&ind.shape!=='target-dash')assert(Math.hypot(ind.endpoint[0]+2,ind.endpoint[2])<=ind.range+1e-6);}}
const e=profiles.Ezreal;assert.equal(Geo.spec(e,'Q').range,12);assert.equal(Geo.spec(e,'E').movementRange,4.75);assert.equal(Geo.spec(e,'E').radius,7.5,'secondary acquisition radius must not become blink distance');assert(Geo.spec(e,'R').global);assert.equal(Geo.spec(profiles.Tristana,'AA',{level:15}).range,6.85);
for(const[name,slot,distance]of[['Ezreal','E',4.75],['Lucian','E',4.25],['Corki','W',5.5],['Zeri','E',3]]){const s=Practice.create(profiles[name],{movements:Fight.MOVEMENT});const ind=Practice.aim(s,slot,[100,0,0]);assert.equal(ind.range,distance);assert(Practice.cast(s,slot,[100,0,0]));const endpoint=ind.endpoint;Practice.step(s,3);assert(Math.hypot(s.hero[0]-endpoint[0],s.hero[2]-endpoint[2])<1e-6,'shown endpoint equals landed position');}
const recoil=Geo.indicator(profiles.Caitlyn,'E',[-2,0,0],[2,0,0],[2,0,0],{},Fight.MOVEMENT);assert(recoil.endpoint[0]<-2);assert(Geo.castTarget(recoil,[2,0,0])[0]>-2,'recoil retreats while net fires forward');assert.equal(recoil.movementVerified,false);assert.equal(Geo.spec(profiles.Vayne,'Q').movementRange,null,'missing WR distance remains missing');
(async()=>{const{GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js'),{clone}=await import('three/addons/utils/SkeletonUtils.js'),Avatar=require('../assets/marksman-3d/baked-avatar.js');const manifest=JSON.parse(fs.readFileSync('assets/marksman-3d/production/manifest.json'));assert.equal(Object.keys(manifest.champions).length,23);let poses=0,skins=0;
for(const[name,p]of Object.entries(profiles)){for(const file of['character.glb','preview.glb']){const b=fs.readFileSync(path.join('assets/marksman-3d/production',p.id,file)),gltf=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');assert.deepEqual(new Set(gltf.animations.map(a=>a.name)),new Set(['Idle','Walk','AA','P','Q','W','E','R']));gltf.scene.traverse(o=>{if(o.isSkinnedMesh){skins++;const a=o.geometry.attributes.skinWeight;for(let i=0;i<a.count;i++)assert(Math.abs(a.getX(i)+a.getY(i)+a.getZ(i)+a.getW(i)-1)<1e-5);}});const avatar=Avatar.createAvatar(T,gltf,clone,p,{software:file==='preview.glb'});assert(avatar.sockets.muzzle);assert(avatar.metrics().joints>=6);for(const action of['Idle','Walk','AA','P','Q','W','E','R'])for(const progress of[.15,.5,.9]){avatar.animate({action,progress,time:progress*1.2});const muzzle=avatar.sockets.muzzle.getWorldPosition(new T.Vector3());assert(muzzle.toArray().every(Number.isFinite));assert(muzzle.length()<10,'socket stays within authored character');avatar.root.traverse(o=>{if(o.isMesh&&!o.isSkinnedMesh)assert([...o.geometry.attributes.position.array].every(Number.isFinite));});poses++;}avatar.root.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});}}
console.log('PASS: 23 full + CPU skinned models / 184 clips / '+poses+' finite poses / '+skins+' skin batches / WR geometry / rank-level range / exact blink-dash endpoints / recoil direction / explicit unresolved ranges');})().catch(e=>{console.error(e);process.exit(1)});
