'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const D=require('../assets/marksman-3d/duel.js'),P=require('../assets/marksman-3d/practice.js'),F=require('../assets/marksman-3d/fight.js');
const C=JSON.parse(fs.readFileSync('app-data/practice.json')).champions;
function duel(name='Ezreal',options={}){const enemy=name==='Ezreal'?'Jinx':'Ezreal',d=D.create({...C[name],name},{...C[enemy],name:enemy},{movements:F.MOVEMENT,distance:500,...options});d.bot.next=Infinity;d.enemy.health.max=d.enemy.health.hp=20000;return d;}
function run(d,seconds){const count=Math.round(seconds/D.DT);for(let i=0;i<count;i++)D.step(d,D.DT);}
const close=(a,b,msg)=>assert(Math.abs(a-b)<1e-7,`${msg}: ${a} vs ${b}`);
// Resources are spent only on successful legal casts. Failed casts/approach inputs cost nothing.
{const d=duel(),s=d.player;s.resource.mana=0;assert(!P.cast(s,'Q'));assert.equal(s.deadlines.Q,undefined);assert.equal(s.events.length,0);run(d,1);close(s.resource.mana,s.resource.manaRegen,'mana regeneration');}
{const d=duel('Jinx',{distance:1400}),s=d.player;assert(P.cast(s,'Q'));const mana=s.resource.mana;assert(!P.cast(s,'AA'));assert.equal(s.resource.mana,mana,'out of range rocket does not spend mana');}
// Ezreal: real Q cooldown reduction and Spell Force only on a landed damaging ability.
{const d=duel(),s=d.player,base=P.stats(s).as;s.resource.mana=500;assert(P.cast(s,'Q'));run(d,.8);close(s.deadlines.Q,C.Ezreal.practice.slots.Q.cooldown[3]-1.5,'Q refund');assert.equal(s.combat.stacks,1);close(P.stats(s).as,base+C.Ezreal.practice.as_ratio*.13,'Spell Force AS');}
{const d=duel(),s=d.player;assert(P.cast(s,'Q',[s.hero[0],0,8]));run(d,1);assert.equal(s.combat.stacks,0);assert.equal(s.deadlines.Q,C.Ezreal.practice.slots.Q.cooldown[3]);}
{const d=duel(),s=d.player;s.resource.mana=500;P.cast(s,'W');run(d,1);assert.equal(s.combat.stacks,0,'mark alone does not add the reference damage passive');assert(d.enemy.health.mark);P.cast(s,'Q');run(d,1);close(s.resource.mana,500-50-45+90+s.resource.manaRegen*d.time,'W ability detonation mana');assert.equal(d.enemy.health.mark,null);assert.equal(s.log.filter(x=>x.slot==='W detonation').length,1);}
{const d=duel(),s=d.player;s.resource.mana=500;P.cast(s,'W');run(d,1);P.cast(s,'AA');run(d,1);assert(s.log.some(x=>x.slot==='W detonation'));close(s.resource.mana,500-50+s.resource.manaRegen*d.time,'reference AA detonation gives no mana refund');}
{const d=duel(),s=d.player;P.cast(s,'Q');run(d,.8);P.cast(s,'E');run(d,1);P.cast(s,'R');run(d,1.6);P.cast(s,'Q');run(d,1);assert.equal(s.combat.stacks,4);run(d,9);assert.equal(s.combat.stacks,0);close(P.stats(s).as,C.Ezreal.practice.levels.as[14],'passive expires');}
// Arcane Shift blinks, acquires the lone nearby enemy at release, then sends a targeted bolt.
{const d=duel(),s=d.player;P.cast(s,'E',d.enemy.hero);run(d,1);assert(s.log.some(x=>x.slot==='E'&&x.dealt));assert(s.hero[0]>0);}
{const d=duel('Ezreal',{distance:1800}),s=d.player;P.cast(s,'E',[-11,0,0]);run(d,2);assert(!s.log.some(x=>x.slot==='E'&&x.dealt));assert.equal(s.combat.stacks,0);}
// Jinx: minigun gains/decays stacks, toggle is free, rockets spend mana per shot and gain range.
{const d=duel('Jinx'),s=d.player;P.holdAttack(s,true);run(d,3);P.holdAttack(s,false);s.pending=null;run(d,.5);assert.equal(s.combat.stacks,3);close(P.stats(s).bonusAS,1.1,'rank four minigun stacks');const until=s.combat.stackUntil;run(d,until-s.time+.05);assert.equal(s.combat.stacks,2);run(d,2);assert.equal(s.combat.stacks,1);run(d,2);assert.equal(s.combat.stacks,0);}
{const d=duel('Jinx'),s=d.player,base=P.stats(s).range;s.resource.mana=500;assert(P.cast(s,'Q'));assert.equal(s.resource.mana,500);assert.equal(P.stats(s).range,base+125);assert(P.cast(s,'AA'));close(s.resource.mana,480,'rocket cost');assert.equal(P.frame(s,{particles:true}).effects.find(e=>e.slot==='AA').empowered,'rocket','rocket has its own visual');run(d,1);const hit=s.log.find(x=>x.slot==='AA'&&x.dealt);close(hit.parts.physical.raw,C.Jinx.practice.attack.damage.physical[14]*1.12,'rocket damage');s.resource.mana=0;s.deadlines.AA=s.time;P.cast(s,'AA');assert.equal(s.combat.weapon,'minigun','low mana falls back');assert.equal(P.stats(s).range,base);}
{const d=duel('Jinx'),s=d.player;s.resource.mana=500;P.cast(s,'Q');P.cast(s,'AA');assert(P.cast(s,'W'));close(s.resource.mana,420,'cancelling rocket windup refunds its 20 mana');}
// Zap slow changes legal walking speed and expires. Chompers wait, persist, root once, then vanish.
{const d=duel('Jinx'),enemy=d.enemy;P.cast(d.player,'W');run(d,1);close(P.stats(enemy).ms,C.Ezreal.practice.levels.ms[14]*.4,'rank four Zap slow');run(d,2);close(P.stats(enemy).ms,C.Ezreal.practice.levels.ms[14],'slow expires');}
{const d=duel('Jinx'),s=d.player,enemy=d.enemy;P.cast(s,'E',enemy.hero);run(d,.9);assert.equal(s.log.filter(x=>x.slot==='E'&&x.dealt).length,0);run(d,.2);assert.equal(s.log.filter(x=>x.slot==='E'&&x.dealt).length,1);assert(enemy.combat.rootUntil>enemy.time);assert.equal(P.stats(enemy).ms,0);const at=enemy.hero.slice(),mana=enemy.resource.mana;assert(!P.cast(enemy,'E'));assert.equal(enemy.resource.mana,mana,'root blocks blink without spending mana');P.move(enemy,[-3,0,2]);run(d,.5);assert.deepEqual(enemy.hero,at,'root stops walking');run(d,2);assert(P.stats(enemy).ms>0);assert.equal(s.log.filter(x=>x.slot==='E'&&x.dealt).length,1);}
{const d=duel('Jinx'),s=d.player,enemy=d.enemy;P.cast(s,'E',[enemy.hero[0],0,5]);run(d,2);P.move(enemy,[enemy.hero[0],0,5]);run(d,2);assert(s.log.some(x=>x.slot==='E'&&x.dealt),'late entry hits armed trap');}
{const d=duel('Jinx'),s=d.player,enemy=d.enemy;P.cast(s,'E',[enemy.hero[0],0,5]);run(d,5.2);P.move(enemy,[enemy.hero[0],0,5]);run(d,2);assert(!s.log.some(x=>x.slot==='E'&&x.dealt),'expired trap cannot hit');}
// The execute reads missing HP at impact, uses the reference lower bound, and rewards a kill.
{const d=duel('Jinx'),s=d.player,enemy=d.enemy;enemy.health.max=2000;enemy.health.hp=900;P.cast(s,'R');run(d,.3);enemy.health.hp=600;run(d,1);const h=s.log.find(x=>x.slot==='R'&&x.dealt);assert(h);assert(h.parts.physical.raw>450&&h.parts.physical.raw<535,'impact-time missing health, not cast-time HP');}
{const d=duel('Jinx'),s=d.player;d.enemy.health.hp=1;s.resource.mana=100;P.cast(s,'AA');run(d,1);assert.equal(d.result,'victory');assert(s.combat.excitedUntil>s.time);assert(s.resource.mana>100,'Get Excited refunds missing mana');}
// No private cooldowns leak into observations; knowledge is learned only after reaction delay.
{const d=duel();d.bot.next=0;P.cast(d.player,'E',[-7,0,0]);run(d,.1);assert.equal(d.bot.knownCooldowns.E,undefined);run(d,.5);assert(d.bot.knownCooldowns.E>10);const view=D.publicActor(d.player);assert(!('deadlines' in view));assert(!('destination' in view));}
console.log('PASS Ezreal/Jinx mechanics: resources, Q/W/E, passive stacks, weapons, rockets, decay, slow/root, persistent traps, execute, kill reward, observed cooldowns');

// Both health HUDs receive display-safe mark durations, never raw combat records.
for(const side of ['player','enemy']){const d=duel(side==='player'?'Ezreal':'Jinx'),s=d[side];assert(P.cast(s,'W'));run(d,1);const victim=side==='player'?d.enemy:d.player,health=D.frame(d)[side==='player'?'dummy':'playerHealth'];assert(victim.health.mark);close(health.mark.remaining,victim.health.mark.until-victim.time,'mark HUD countdown');assert.doesNotThrow(()=>health.mark.remaining.toFixed(1));assert(!('raw' in health.mark));const remaining=health.mark.remaining;run(d,.5);close(D.frame(d)[side==='player'?'dummy':'playerHealth'].mark.remaining,remaining-.5,'countdown advances');run(d,5);assert.equal(D.frame(d)[side==='player'?'dummy':'playerHealth'].mark,null);}

{const d=duel();P.cast(d.player,'W');for(let i=0;i<240&&!d.enemy.health.mark;i++)D.step(d,D.DT);assert(D.frame(d,{particles:true}).impacts.some(h=>h.mark),'W application has a distinct impact');P.cast(d.player,'Q');for(let i=0;i<240&&!d.player.log.some(h=>h.slot==='W detonation');i++)D.step(d,D.DT);assert(D.frame(d,{particles:true}).impacts.some(h=>h.detonation),'W detonation gets its own impact');}
