'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),T=require(require.resolve('three',{paths:[require('node:path').join(__dirname,'../mobile')]}));
const S=require('../assets/marksman-3d/scene.js'),E=require('../assets/marksman-3d/effects.js'),D=require('../assets/marksman-3d/duel.js'),P=require('../assets/marksman-3d/practice.js'),B=require('../assets/marksman-3d/duel-bot.js'),F=require('../assets/marksman-3d/fight.js');
const C=JSON.parse(fs.readFileSync('app-data/practice.json')).champions,profile=n=>({...C[n],name:n});
// Shared articulated assets, deterministic walking and attack poses, no idle foot sliding.
{const factory=S.createLaneModels(T),u={side:0,ranged:false,position:[1,0,2],hp:100,max:100,moving:true,gait:Math.PI/2,facing:.7,lastAttack:null},a=factory.create(u),b=factory.create({...u,side:1,ranged:true});assert.equal(a.name,'Lane_Melee');assert.equal(b.name,'Lane_Caster');S.faceActor(a,.7,'W',1);factory.update(a,u,1);assert.equal(a.rotation.y,.7);assert(a.userData.actor.legs[0].rotation.x>0);assert(a.userData.actor.legs[1].rotation.x<0);factory.update(a,{...u,moving:false,lastAttack:.8},1);assert.equal(a.userData.actor.legs[0].rotation.x,0);assert(a.userData.actor.arms[1].rotation.x<0);const pose=a.userData.actor.arms[1].rotation.x;factory.update(a,{...u,moving:false,lastAttack:.8},1);assert.equal(a.userData.actor.arms[1].rotation.x,pose);const ga=new Set(),gb=new Set();a.traverse(o=>{if(o.isMesh)ga.add(o.geometry);});b.traverse(o=>{if(o.isMesh)gb.add(o.geometry);});assert([...ga].every(g=>gb.has(g)),'waves share geometries');assert(factory.geometries.length<=5);assert(factory.materials.length<=10);for(const g of factory.geometries)g.dispose();for(const m of factory.materials)m.dispose();}
// Walk rotations cross the angle seam along the shortest arc; casts face their exact aim immediately.
{const root=new T.Group();S.faceActor(root,Math.PI-.01,'Walk',0);S.faceActor(root,-Math.PI+.01,'Walk',.02);assert(root.rotation.y>Math.PI-.01);S.faceActor(root,-1.4,'Q',.03);assert.equal(root.rotation.y,-1.4);}
// Pilot projectile bodies remain flat; Jinx AA/W/R and Ezreal E have distinct silhouettes.
{const scene=new T.Scene(),fx=E.createEffects(T,scene,{budget:600}),source=new T.Vector3(0,1.1,0),target=new T.Vector3(5,1.1,0),counts=[];for(const slot of['AA','W','R']){fx.begin();fx.draw(profile('Jinx'),slot,{source,target,release:.3,impactAt:.8,progress:.5,age:.4});fx.finish();const meshes=scene.children[0].children.filter(o=>o.isMesh&&o.visible);counts.push(meshes.length);assert(meshes.length>0);for(const m of meshes){assert(Math.abs(m.position.y-1.1)<1e-8,'Jinx projectile geometry is gravity-free');assert(m.position.toArray().every(Number.isFinite));}}assert(new Set(counts).size===3);fx.begin();fx.draw(profile('Ezreal'),'E',{source,target,release:.3,impactAt:.8,progress:.6,age:.5,start:new T.Vector3(-2,0,0),end:new T.Vector3(0,0,0)});fx.finish();assert(scene.children[0].children.some(o=>o.isMesh&&o.visible),'blink follow-up bolt renders');fx.dispose();}
// Friendly minion cover never overrides visible tower aggro on the bot itself.
{const d=D.create(profile('Ezreal'),profile('Jinx'),{movements:F.MOVEMENT}),self={...D.selfActor(d.enemy),position:[-16,0,0],hp:1000,max:1000,locked:false},bot=B.create('hard');B.observe(bot,{time:0,enemy:{champion:'Ezreal',position:[-18,0,0],velocity:[0,0,0],hp:1000,max:1000,casts:[],hits:[]},lane:{side:1,ad:100,minions:[{id:'cover',side:1,hp:450,position:[-18,0,1]}],towers:[{id:'t',side:0,position:[-19,0,0],range:6.5,aggro:'enemy'},{id:'home',side:1,position:[19,0,0],range:6.5}]}});assert.equal(B.decide(bot,self,1).reason,'tower retreat');}
// A full three-minute lane run for each pilot and difficulty, with health extended only in the fixture.
for(const name of['Ezreal','Jinx'])for(const difficulty of Object.keys(B.MODES)){const d=D.create(profile(name),profile(name==='Ezreal'?'Jinx':'Ezreal'),{lane:true,difficulty,movements:F.MOVEMENT,duration:180});for(const s of[d.player,d.enemy])s.health.max=s.health.hp=1e6;d.player.autoApproach=false;P.holdAttack(d.player,true);for(let i=0;i<720&&!d.finished;i++){D.step(d,.25);if(i%40===0){const f=D.frame(d,{particles:true});assert(f.hero.every(Number.isFinite)&&f.target.every(Number.isFinite));assert(d.lane.units.length<=64);assert(d.lane.shots.length<100);assert(d.bot.history.length<200);assert(d.bot.seenHits.size<100);assert(d.bot.seenCasts.size<100);for(const s of[d.player,d.enemy]){assert(s.events.length<64);assert(s.hits.length<64);assert(s.numbers.length<64);assert(s.resource.mana>=0&&s.resource.mana<=s.resource.max);}}}assert(d.finished);assert.equal(d.result,'timeout');}
console.log('PASS Day 2: articulated shared minions, turn continuity, distinct flat pilot VFX, tower aggro and eight three-minute bounded sessions');
