const assert=require('node:assert/strict'),fs=require('node:fs'),T=require('three');
const HUD=require('../assets/marksman-3d/combat-hud.js'),FX=require('../assets/marksman-3d/effects.js'),Fight=require('../assets/marksman-3d/fight.js');global.MarksmanRig=require('../assets/marksman-3d/rig.js');const {prepareEffectFrame}=require('../assets/marksman-3d/scene.js');
const profiles=JSON.parse(fs.readFileSync('data/marksman-art-direction.json')).champions,abilities=JSON.parse(fs.readFileSync('data/marksman-ability-catalogue.json')).champions,icons=JSON.parse(fs.readFileSync('data/riot/marksman-skill-icons.json')).champions;
for(const [name,p]of Object.entries(profiles)){p.name=name;p.hud={abilities:Object.fromEntries(Object.entries(abilities[name].abilities).map(([s,a])=>[s,{cooldowns:a.cooldown_by_rank}]))};for(const slot of 'PQWER'){assert.match(icons[name].icons[slot],/^data:image\/(webp|png);base64,/);assert(Buffer.from(icons[name].icons[slot].split(',')[1],'base64').length>500);}const events=Fight.eventList(p,1);for(const e of events){const previous=events.filter(x=>x.slot===e.slot&&x.start<e.start).at(-1),cd=HUD.cooldown(p,e.slot);if(previous&&e.slot!=='AA'&&cd!==null)assert(e.start-previous.start>=cd);}for(const time of[0,3,8,14,19,8]){const a=HUD.fightDeadlines(p,events,time),b=HUD.fightDeadlines(p,events,time);assert.deepEqual(a,b);for(const k of Object.keys(a))assert(HUD.remaining(a,k,time)>=0);}}
const p=profiles.Ezreal,ends={};assert(HUD.cast(ends,p,'Q',0));assert(!HUD.cast(ends,p,'Q',2));assert.equal(HUD.remaining(ends,'Q',2),3.5);assert(HUD.cast(ends,p,'Q',5.5));assert.equal(HUD.cooldown(p,'W'),10);assert.equal(FX.effectColor(p,'Q'),'#71e6ff');assert.equal(FX.effectColor(p,'W'),'#ffd948');
const rig=MarksmanRig.createRig(T,p),launch={slot:'Q',progress:.5,release:.35,launchTime:.3325,launchHero:[-1.8,0,0],launchTarget:[2.1,0,0]};let first;
for(const u of [.36,.5,.7,.9,.5]){const anim={time:u*.95,action:'Q',progress:u,speed:0};rig.root.position.set(-1.8,0,0);rig.root.rotation.y=Math.PI/2;MarksmanRig.animateRig(rig,anim);rig.root.updateMatrixWorld(true);const matrices=[];rig.root.traverse(o=>{if(o.isBone)matrices.push(o.matrixWorld.elements.slice());});const f=prepareEffectFrame(T,rig,{...launch,progress:u},new T.Vector3(-1.8,0,0),new T.Vector3(2.1,0,Math.sin(u)),anim);if(!first)first=f;assert(f.source.distanceTo(first.source)<1e-8);assert(f.target.distanceTo(first.target)<1e-8);assert.equal(f.source.y,f.target.y);const after=[];rig.root.traverse(o=>{if(o.isBone)after.push(o.matrixWorld.elements.slice());});assert.deepEqual(matrices,after,'sampling launch must restore current skeleton');
 const fx=FX.createEffects(T,new T.Scene());fx.begin();fx.draw(p,'Q',f);const cone=fx.group.children.find(o=>o.isMesh&&o.visible&&o.geometry.type==='ConeGeometry');if(u>=.8){assert(!cone,'Q has reached impact');assert(fx.group.children.some(o=>o.visible&&o.geometry.type==='TorusGeometry'));fx.dispose();continue;}assert(cone);assert(Math.abs(cone.position.y-f.source.y)<1e-8);assert(cone.position.clone().sub(f.source).cross(f.target.clone().sub(f.source)).length()<1e-8,'straight aim line');fx.dispose();}
for(const name of ['Corki','Jhin']){const p=profiles[name],fx=FX.createEffects(T,new T.Scene()),origin=new T.Vector3(-2,1.3,0),target=new T.Vector3(2,1.3,0);for(const u of[.4,.5,.6,.7]){fx.begin();fx.draw(p,'Q',{source:origin,target,progress:u,age:u});const bomb=fx.group.children.find(o=>o.isMesh&&o.visible&&o.geometry.type==='SphereGeometry');assert(bomb);assert.equal(bomb.position.y,1.3,'no ballistic arc');}fx.dispose();}
console.log('PASS: 115 icons / cooldown cast lock and seek / 23 schedules / frozen launch pose / flat Q and bomb flight / restored skeleton');
// A GLB walking pose must follow gait phase, not jump when the global clock or speed changes.
(async()=>{const {pathToFileURL}=require('node:url'),{GLTFLoader}=await import(pathToFileURL(require.resolve('three/addons/loaders/GLTFLoader.js')).href),{clone}=await import(pathToFileURL(require.resolve('three/addons/utils/SkeletonUtils.js')).href),Avatar=require('../assets/marksman-3d/baked-avatar.js');
 const b=fs.readFileSync('static/marksman-3d/ezreal/character.glb'),gltf=await new Promise((resolve,reject)=>new GLTFLoader().parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'',resolve,reject)),a=Avatar.createAvatar(T,gltf,clone,p),pose=()=>{const out=[];a.root.traverse(o=>{if(o.isBone)out.push(...o.position.toArray(),...o.quaternion.toArray());});return out;};
 for(const slot of ['AA','Q','W','E','R'])for(const yaw of [0,Math.PI/2,Math.PI,-Math.PI/2])for(const progress of [0,.35,.6,1]){a.root.rotation.y=yaw;const before=a.root.quaternion.clone();a.animate({action:slot,progress});assert(a.root.quaternion.angleTo(before)<1e-7,'GLB cast must preserve world facing: '+slot);const forward=new T.Vector3(0,0,1).applyQuaternion(a.root.quaternion);assert(forward.distanceTo(new T.Vector3(Math.sin(yaw),0,Math.cos(yaw)))<1e-7);}
 a.animate({action:'Walk',time:1,gaitPhase:1,loopDuration:.8});const first=pose();a.animate({action:'Walk',time:33,gaitPhase:1,loopDuration:1.1});assert.deepEqual(pose(),first,'global time / changed movement speed cannot warp a fixed gait pose');
 a.animate({action:'Idle',time:33});a.animate({action:'Walk',time:33,gaitPhase:1,loopDuration:1.1});assert.deepEqual(pose(),first,'idle resumes the same gait phase');a.animate({action:'Walk',time:33,gaitPhase:1.1,loopDuration:1.1});assert.notDeepEqual(pose(),first,'actual distance advancement changes the walk pose');console.log('PASS GLB gait: stable phase across clock, speed changes and idle/resume');
 a.animate({live:true,action:'Idle',time:100});const idle=pose();a.animate({live:true,action:'Walk',time:100.02,gaitPhase:1});assert.deepEqual(pose(),idle,'transition begins at previous rendered pose');a.animate({live:true,action:'Walk',time:100.08,gaitPhase:1});const midway=pose();assert.notDeepEqual(midway,idle);a.animate({live:true,action:'Walk',time:100.2,gaitPhase:1});const settled=pose();a.animate({action:'Walk',gaitPhase:1});assert.deepEqual(pose(),settled,'transition settles at the exact clip pose');
 a.animate({live:true,action:'Q',time:100.21,progress:.1,blendSeconds:.04});a.animate({live:true,action:'Q',time:100.23,progress:.2,blendSeconds:.04});const smooth=pose();const frame={...launch,seed:900,progress:.6};prepareEffectFrame(T,a,frame,new T.Vector3(-1.8,0,0),new T.Vector3(2.1,0,0),{live:true,action:'Q',time:100.23,progress:.2,blendSeconds:.04});assert.deepEqual(pose(),smooth,'launch sampling restores the blended live pose');
 console.log('PASS live blending: continuous entry, exact settled pose, isolated launch sampling');

})().catch(error=>{console.error(error);process.exitCode=1;});

// Audio deduplicates events, respects mute, and never creates a context without a gesture.
{let contexts=0,voices=0;const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}}),node=()=>({connect(){},disconnect(){}});class Context{constructor(){contexts++;this.state='running';this.currentTime=1;}resume(){return Promise.resolve();}close(){return Promise.resolve();}createGain(){return{...node(),gain:param()};}createOscillator(){return{...node(),frequency:param(),start(){voices++;},stop(){}};}}
 const audio=FX.createCombatAudio({Context}),state={profile:{name:'Ezreal'},time:1,events:[{slot:'Q',launch:1}],log:[]};audio.update([{state}]);assert.equal(contexts,0);audio.unlock();state.events.push({slot:'W',launch:1});audio.update([{state}]);assert.equal(voices,2);audio.update([{state}]);assert.equal(voices,2,'same event never repeats');audio.setEnabled(false);state.log.push({slot:'W detonation',t:1,dealt:100});audio.update([{state}]);assert.equal(voices,2);audio.setEnabled(true);audio.update([{state}]);assert.equal(voices,2,'unmute never replays old hits');audio.dispose();audio.unlock();assert.equal(contexts,1);}
